### PR TITLE
Added a obama response

### PR DESCRIPTION
**Pull request by AdithaD**
It uses a cubic scaling between 0 and 1 to not be annoying.

### CODE REVIEW

**Comment by lucyyyyyyy** [comment]
Looks good to me 👍

**Review by epetousis — CHANGES_REQUESTED** [review]
Just a couple of issues related to code linting, and a concern that I've outlined below.

**Comment by AdithaD** [comment]
I added the discriminator. For the linting, my ESLint extension is throwing a fit about line endings. But I have seem to fixed it's indentation setting.

**Review by epetousis — APPROVED** [review]
Looks good. Just need to move out that unary incrementor and we're good, I reckon.

**Pull request merged**
